baseURL = "http://wiki.ninini.net/"
languageCode = "zh-cn"
title = "Wow! Cool Team Wiki"
theme = "hugo.386-master"


[menu]

    [[menu.shortcuts]]
    name = "<i class='fab fa-zhihu'></i>"
    url = ""
    weight = 10

    [[menu.shortcuts]]
    name = "<i class='fab fa-github'></i>"
    url = ""
    weight = 9
